### ISSUE TITLE
Bloom filter link reference unexpected location

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-specification#2]
I'm not sure if this is right, but the `[Bloom Filters](/objects/bloom__filter)` reference in home.md refers to a top-level "objects" folder, which doesn't exist.

I don't know if this is a bug, but my link checker complained and the path didn't match my expectations.

**Comment by monsterbitar** [comment]
The link also uses double underscore (__) instead of a single underscore (_) which is what I would've expected it to use.

**Comment by thesquaregroot** [comment]
This has been fixed.
