### ISSUE TITLE
Inaccurate size for input sequence number

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-specification#27]
Paul Chandler found an error in the documentation, on `/protocol/blockchain/transaction/transaction-signing` in the `Bitcoin Cash Signatures` section. The table lists:

> input sequence number | 8 bytes

But according to https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/replay-protected-sighash.md is should be 4 bytes.

**Comment by monsterbitar** [comment]
Addressed by https://github.com/SoftwareVerde/bitcoin-cash-specification/pull/28

**Comment by joshmg** [comment]
#28 was merged today; closing.  Thanks for pointing this out and for the subsequent PR.
