### ISSUE TITLE
xverack referenced but does not exist.

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-specification#3]
home.md references `[xverack](/protocol/p2p/xverack)` which does not exist.

I'm not sure if you want "missing / broken links" reported as bugs, but this is a very clean issue in the sense that it seems to be a fully valid and normal link that just doesn't exist.

**Comment by thesquaregroot** [comment]
The pages for all of the listed message types have now been created.
