### ISSUE TITLE
Incorrect markup for sub/sup

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-specification#4]
On `/protocol/forks/hf-20171113` there are some which are displayed as `Let B<sub>n</sub> be`.
On `/protocol/blockchain/proof-of-work/difficulty-adjustment-algorithm` similar formulas are presented but they show the sub/sup parts correctly.

The `/protocol/forks/hf-20171113` should be updated the match the structure of the other example that works.

**Comment by thesquaregroot** [comment]
Fixed in 0708f55d.
