### ISSUE TITLE
Prevent rendering errors by not using strike-through symbol for bitwise NOT

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-specification#5]
In the blockchain/proof-of-work page, there's a formula that uses `~` sign, which is later explained on the same line. This result in some text that is wrapped in `~` signs which according to markdown structure should result in the text being strike-through.

I've verified that replacing the `~` sign with the appropiate HTML entitiy (&#126;) renders identically for the end-user, but increases complexity on the maintainers / editors of the content.

I'm torn on what's the best solution - the trade off seems to be between protability (markdown that works everywhere) and maintainance cost (markdown that's not immidiately obvious how to edit)

**Comment by monsterbitar** [comment]
On second though, change it so that it doesn't use use `<code>` HTML tags for the formula but using ` (backtick) encapsulation for both the code and the sign reference makes it render correctly in my renderer.

I assume the reason for the editor to manually enter the HTML `<code>` tag is that the current renderer used by reference.cash/bitcoinprotocol.cash had similar issues.

If that is not the case, then it should be a simple solution to replace the `<code>` HTML tags with the apporopiate backticks instead.

**Comment by thesquaregroot** [comment]
Should be fixed with 14da15f.
