### ISSUE TITLE
Standard transaction description lacks size limit for data outputs.

### ISSUE THREAD

**Issue by monsterbitar** [SoftwareVerde/bitcoin-cash-specification#8]
This page: https://documentation.cash/protocol/blockchain/transaction-validation/network-level-validation-rules

Lists "Have at most one data output", but reading on the data output part of the page does not inform the user about the limitations of the data output.

**Comment by monsterbitar** [comment]
If this is because the size limit is not a standardness rule, I would suggest adding a helpful link to further related information as to help reader more easily find this information.

**Comment by thesquaregroot** [comment]
Added to the network-level-validation-rules page in ad613a9.
